DEFAULT_SAMPLE_RATE = 48000

DEFAULT_KEY = "D"
DEFAULT_SCALE = "minor"

DEFAULT_SNAP_STRENGTH = .8
DEFAULT_SMEAR = 0.4
DEFAULT_BIN_SMOOTHING = True

DEFAULT_DISTORTION_MODE = "wavefold"

DEFAULT_LIMITER_ON = True
DEFAULT_LIMITER_CEILING_DB = -1.0
DEFAULT_DRY_WET = 1.0
